### ISSUE TITLE
Firefox fails to run (errors) when using frozen-moment with webpack

### ISSUE THREAD

**Issue by ericlau-solid** [WhoopInc/frozen-moment#21]
Issue only happens on firefox. Chrome runs fine. Only happens using frozen-moment. Moment itself webpacks fine with same settings.

![capture](https://cloud.githubusercontent.com/assets/8011182/16126172/e4dcf964-33ab-11e6-8b05-52d8bbff8942.PNG)

Line with syntax error reads:

```
//! moment.js locale configuration
//! locale : Arabic Saudi Arabia (ar-sa)
//! author : Suhail Alkowaileet : https://github.com/xsoh
!function(e,t){t(n(6))}(this,function(e){"use strict";var t={1:"?",2:"?",3:"?",4:"?",5:"?",6:"?",7:"?",8:"?",9:"?",0:"?"},n={"?":"1","?":"2","?":"3","?":"4","?":"5","?":"6","?":"7","?":"8","?":"9","?":"0"},r=e.defineLocale("ar-sa",{months:"?????_??????_????_?????_????_?????_?????_?????_??????_??????_??????_??????".split("_"),monthsShort:"?????_??????_????_?????_????_?????_?????_?????_??????_??????_??????_??????".split("_"),weekdays:"?????_???????_????????_????????_??????_??????_?????".split("_"),weekdaysShort:"???_?????_??????_??????_????_????_???".split("_"),weekdaysMin:"?_?_?_?_?_?_?".split("_"),longDateFormat:{LT:"HH:mm",LTS:"HH:mm:ss",L:"DD/MM/YYYY",LL:"D MMMM YYYY",LLL:"D MMMM YYYY HH:mm",LLLL:"dddd D MMMM YYYY HH:mm"},meridiemParse:/?|?/,isPM:function(e){return"?"===e},meridiem:function(e,t,n){return 12>e?"?":"?"},calendar:{sameDay:"[????? ??? ??????] LT",nextDay:"[??? ??? ??????] LT",nextWeek:"dddd [??? ??????] LT",lastDay:"[??? ??? ??????] LT",lastWeek:"dddd [??? ??????] LT",sameElse:"L"},relativeTime:{future:"?? %s",past:"??? %s",s:"????",m:"?????",mm:"%d ?????",h:"????",hh:"%d ?????",d:"???",dd:"%d ????",M:"???",MM:"%d ????",y:"???",yy:"%d ?????"},preparse:function(e){return e.replace(/[??????????]/g,function(e){return n[e]}).replace(/?/g,",")},postformat:function(e){return e.replace(/\d/g,function(e){return t[e]}).replace(/,/g,"?")},week:{dow:6,doy:12}});return r})},function(e,t,n){
```

**Comment by butterflyhug** [comment]
@ericlau-solid Thanks for the report.  This seems likely to be an issue with how I set up CommonJS module support, which was focused on the Node environment rather than tools like Webpack.

Can you try the code in #22 and let me know if that helps?

**Comment by butterflyhug** [comment]
@ericlau-solid Did you ever get a chance to try #22?  That said, the code where you're getting a syntax error is one of the core library's locales, so I'm not sure why that'd webpack differently with Frozen Moment than without.

Also, FYI, I'm [working with Moment's maintainers](https://github.com/moment/moment-rfcs/pull/2) to get an officially-distributed and supported version of Frozen Moment's functionality.  I'm hopeful that moving this functionality closer to core will also help webpack do the right thing.

**Comment by ericlau-solid** [comment]
I have no time or chance. Have serious health issue that I must focus on.

Eric Lau - Gmail

On Sat, Jul 16, 2016 at 7:48 AM -0700, "Lucas Sanders" notifications@github.com wrote:

@ericlau-solid Did you ever get a chance to try #22?  That said, the code where you're getting a syntax error is one of the core library's locales, so I'm not sure why that'd webpack differently with Frozen Moment than without.

Also, FYI, I'm working with Moment's maintainers to get an officially-distributed and supported version of Frozen Moment's functionality.  I'm hopeful that moving this functionality closer to core will also help webpack do the right thing.

**Comment by butterflyhug** [comment]
Okay, no problem.  Good luck with your recovery!

I'll close this issue for now, but feel free to reopen and/or comment on #22 if you ever get back to this in the future.
