### ISSUE TITLE
Frozen Moment should support all browsers supported by Moment

### ISSUE THREAD

**Issue by butterflyhug** [WhoopInc/frozen-moment#9]
"Currently the following browsers are used for the ci system: IE8, IE9 on Windows 7, stable Chrome on Windows XP, Safari 10.8 on Mac and stable Firefox on Linux."  http://momentjs.com/docs/

The current code uses `Object.create()` and `Array.prototype.indexOf()`, neither of which are supported by IE8.

**Comment by pitaj** [comment]
Not a full polyfill, but stand-in for `Object.create`

``` js
var create = Object.create || function(proto) {
  var obj = {};
  obj.__proto__ = proto;

  return obj;
};
```

Not a full polyfill, but stand-in for `Array#indexOf`

``` js
// call this with `.call`
var indexOf = Array.prototype.indexOf || function(value){
  var l = this.length, i = 0;
  while(i < l){
    if(this[i] === value){
      return i;
    }
    i += 1;
  }
  return -1;
};
```

**Comment by butterflyhug** [comment]
Yep, definitely.  Those look good enough for our purposes, except `indexOf` needs to return `-1` if the element is not found.  (Alternatively, we could re-write this as a proper `contains` function instead of sticking with `Array.indexOf`.)

I'd happily accept a PR along these lines, assuming our tests pass on IE8.

**Comment by pitaj** [comment]
Yeah, edited the `indexOf` example to `return -1`. I also think you mean `Array#includes`, not contains, as contains doesn't exist afaik?

Here's an example for includes

``` js
// call this with `.call`
var includes = Array.prototype.includes || function(value){
  var l = this.length, i = 0; 
  while(i < l){
    if(this[i] === value){
      return true;
    }
  }
  return false;
};
```

One thing to note is that in both cases, my stand-in has to be called with `.call` on the Array. This could be avoided, what do you prefer?

I'm about to start making changes, so figure out whether you'd like `indexOf` or `includes` and whether you want `.call` or not.

**Comment by butterflyhug** [comment]
Awesome, thanks!  I forgot that ES7 is adding `includes`, so I was making up a name when I said "contains".

Let's go with `includes` and `.call`.

**Comment by pitaj** [comment]
Submitted PR #11 

Try it out

**Comment by butterflyhug** [comment]
After #11, we seem to be in good shape.  Thanks again, @pitaj!
